### ISSUE TITLE
Mobile App master issue

### ISSUE THREAD

**Issue by jusleg** [jusleg/qc-vaccine-pass#5]
* [ ] implement qr code scanner
* [ ] send api request to `/api/pass` with `name`, `location`, and `qr_content` (raw shc payload)
* [ ] Validate shc to ensure two vaccines were given (https://github.com/fproulx/shc-covid19-decoder for context)
* [ ] App clips?!
